//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleIV
{
    using System;
    using System.Collections.Generic;
    
    public partial class C1077982_Ciudadano
    {
        public int Id { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Sexo { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string LugarNacimiento { get; set; }
        public string TipoSangre { get; set; }
        public System.DateTime FechaExpiracion { get; set; }
        public string Ocupacion { get; set; }
        public string EstadoCivil { get; set; }
        public string Nacionalidad { get; set; }
        public string Firma { get; set; }
        public string Foto { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string CodigoPostal { get; set; }
    }
}
